name: BizUnderdogToTopdog
favicon: null
layout_spectrum: 0.33878100104629993
typography_spectrum: 0.17922143498435616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.330241386545822
  lightness: 0.10906056384555995
  saturation: 0.3446710032876581
  rhythmicContrast: 0.3494619866833091
purpose: []
