name: BizUnderdogToTopdog
favicon: null
layout_spectrum: 0.4717
typography_spectrum: 0.28277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000b00'
    - '#9cb5d6'
    - '#447f00'
    - '#0032a5'
  brandStrength: 0.5
  lightness: 0.125
  saturation: 0.3446710032876581
  rhythmicContrast: 0.3494619866833091
purpose: []
