name: BizUnderdogToTopdog
favicon: null
layout_spectrum: 0.48708
typography_spectrum: 0.0729
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8ed1fc'
    - '#034e6b'
    - '#2a839a'
    - '#83463a'
    - '#141317'
  brandStrength: 0.25
  lightness: 0.10906056384555995
  saturation: 0.3446710032876581
  rhythmicContrast: 0.3494619866833091
purpose: []
